### ISSUE TITLE
有上传jetbrains么?

### ISSUE THREAD

**Issue by dreamlivemeng** [zhonghanwen/AndroidProguardPlugin#1]
有上传jetbrains么?如果有上传jetbrains,可以pull requests到这里面去收录上。https://github.com/dreamlivemeng/androidstudio-plugins

**Comment by zhonghanwen** [comment]
@dreamlivemeng 有上传，但是一直是Wait for approve状态

**Comment by zhonghanwen** [comment]
已更新。
