### ISSUE TITLE
所有类名没有被混淆

### ISSUE THREAD

**Issue by menghuit** [zhonghanwen/AndroidProguardPlugin#10]
`#微信支付
-keep class com.tencent.mm.sdk.openapi.WXMediaMessage {*;}
-keep class com.tencent.mm.sdk.openapi.** implements com.tencent.mm.sdk.openapi.WXMediaMessage$IMediaObject {*;}
-keep class com.tencent.wxop.** { *; }
-dontwarn com.tencent.mm.**
-keep class com.tencent.mm.**{*;}
// 这样会保护所有的类名，反编的时候，类名看的清清楚楚
-keepclasseswithmembernames class ** {
}
-keepattributes Signature`

**Comment by zhonghanwen** [comment]
@menghuit  有些类或者类名是需要被保留。

**Comment by zhonghanwen** [comment]
@menghuit 我看错了，已删掉后面的这两个。感谢您的反馈~
