### ISSUE TITLE
插件

### ISSUE THREAD

**Issue by zhaoxiuyu** [zhonghanwen/AndroidProguardPlugin#13]
这个插件还在维护吗？

**Comment by zhonghanwen** [comment]
@zhaoxiuyu 有什么问题？

**Comment by zhaoxiuyu** [comment]
你好。
所有依赖的jar  或者 aar  都需要配置 不能 混淆吗。如果需要，应该如何去配置，
我看配置了很多东西，有些没有用上，不会有什么影响吗。

**Comment by zhonghanwen** [comment]
@zhaoxiuyu 所依赖的jar包不一定全部都需要配置，打release包的时候，看打印出的Log日志，如果提示warn或者error的话，那就需要使用keep保留。

**Comment by zhaoxiuyu** [comment]
我反正是醉了，加不加其他jar 的配置  ，都不能打包。
![image](https://cloud.githubusercontent.com/assets/16554580/17584769/f68aa2ae-5fea-11e6-9b44-e25b20c95ade.png)

**Comment by zhonghanwen** [comment]
@zhaoxiuyu 大哥，你的proguard-rules.pro文件的478行有错~
