### ISSUE TITLE
怎么安装

### ISSUE THREAD

**Issue by ydmmocoo** [zhonghanwen/AndroidProguardPlugin#14]
能问下这个如何安装吗？下载下来里面好几个jar包，只安装AndroidProguard.jar会报错

**Comment by zhonghanwen** [comment]
@ydmmocoo [here](http://7xrnko.com1.z0.glb.clouddn.com/androidproguard1.gif)

**Comment by zhonghanwen** [comment]
报错可以看一下这个 #4
