### ISSUE TITLE
Poi 操作Excel混淆参数

### ISSUE THREAD

**Issue by wukaikailive** [zhonghanwen/AndroidProguardPlugin#17]
我只用到Poi的Excel部分，并且不涉及到写操作。
使用的版本是3.12，但不是官方的，而是使用了别人修改过的以方便在安卓上使用（https://github.com/andruhon/android5xlsx）。
发上来给大家参考下：
# office

-dontwarn com.microsoft.schemas.**
-dontwarn org.etsi.uri.**
-dontwarn org.openxmlformats.schemas.**
-dontwarn schemasMicrosoftComVml.**
-dontwarn schemasMicrosoftComOfficeOffice.**
-dontwarn schemasMicrosoftComOfficeExcel.**
-dontwarn org.w3.x2000.x09.xmldsig.**
# poi

-dontwarn org.apache.poi.**
-dontwarn com.bea.xml.stream.**
-keep class org.apache.poi.ss.formula.**{*;}
-keep class org.apache.poi.hssf.record.** {_;}
-keep class org.apache.poi.openxml4j.__{_;}
-keep class org.apache.poi.xssf.**{*;}
-keep class com.bea.xml.stream.**{_;}
-keep class openxmlformats.schems.__{_;}
-keep class org.apache.xmlbeans.impl.**{*;}
-keep class  schemaorg_apache_xmlbeans.system.**{*;}

**Comment by zhonghanwen** [comment]
非常感谢你的贡献
