### ISSUE TITLE
感觉意义不是很大

### ISSUE THREAD

**Issue by ityulong** [zhonghanwen/AndroidProguardPlugin#19]
只是有一个模板，并不能根据自己的程序进行定制混淆，混淆运行之后会有很多错误

**Comment by zhonghanwen** [comment]
@ityulong 混淆需要根据你的实际的项目来处理，至少定制混淆这个问题之前我也考虑过的！混淆运行之后会有很多错误问题，需要你处理就可以了！

**Comment by zhonghanwen** [comment]
意义不大也没所谓！帮到人就可以了！
![image](https://cloud.githubusercontent.com/assets/12220537/19723503/19f8fea8-9bae-11e6-83e1-4a231bf36989.png)
