### ISSUE TITLE
安装出错

### ISSUE THREAD

**Issue by silence3613** [zhonghanwen/AndroidProguardPlugin#2]
![image](https://cloud.githubusercontent.com/assets/16849704/15988620/512ef7fe-308a-11e6-93e1-185d6f5e6517.png)

**Comment by zhonghanwen** [comment]
@silence3613 估计你的Jdk版本比我的低造成的，我使用JDK8的 ![](http://zhuangbi.idagou.com/i/2016-05-21-8055f6762a968bae06ce9584098b4240.jpg)

**Comment by silence3613** [comment]
我切换下JDK版本看看。

**Comment by AegisLee** [comment]
Android Studio 2.1.2 ， JDK 1.8 ， 也是安装失败了， 提示和以上截图类似；

**Comment by zhonghanwen** [comment]
@AegisLee 我试一下编译成低版本的，你重新下载试一下成不成？
