### ISSUE TITLE
update glide

### ISSUE THREAD

**Issue by chenyongta** [zhonghanwen/AndroidProguardPlugin#26]
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public class * extends com.bumptech.glide.module.AppGlideModule
-keep public enum com.bumptech.glide.load.resource.bitmap.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}

# for DexGuard only
-keepresourcexmlelements manifest/application/meta-data@value=GlideModule

**Comment by zhonghanwen** [comment]
已更新，感谢您的贡献～～
