### ISSUE TITLE
greendao crash 本地没有这个jar

### ISSUE THREAD

**Issue by ihrthk** [zhonghanwen/AndroidProguardPlugin#5]
# #  ######## greenDao混淆
# # -------------------------------------------

-libraryjars libs/greendao-1.3.7.jar
-keep class de.greenrobot.dao.*\* {*;}
-keepclassmembers class \* extends de.greenrobot.dao.AbstractDao {
    public static Java.lang.String TABLENAME;
}

**Comment by zhonghanwen** [comment]
@ihrthk 已将-libraryjars libs/greendao-1.3.7.jar这句去掉，感谢您的反馈~
